### ISSUE TITLE
[FR] Improving the inline code visibility

### ISSUE THREAD

**Issue by icytree** [oleeskild/digitalgarden#11]
First of all, thank you very much for the great plugin (and website template) it is very nice ! 

My request is regarding how inline code displays, I feel like it does not stand out as much as I would like it to. Something like the default format in Obsidian would be just right. Here's some pictures to better highlight my point : 
On the website : ![image](https://user-images.githubusercontent.com/80559262/163071675-454c2bd2-8481-4fc4-b823-1c684fa0592e.png)
In Obsidian : 
![image](https://user-images.githubusercontent.com/80559262/163072787-96700f21-ae68-4174-a0ca-c7c2f6b15525.png)
Another slight variant that could be nice : ![image](https://user-images.githubusercontent.com/80559262/163072748-66b8c56a-0f7d-4098-963d-d5f7204cff70.png)

I personally really don't mind the color, I just would like it to stand out better from regular text.

**Comment by oleeskild** [comment]
Thanks for the input! I agree, I've released a new version with an inline code style similar to what obsidian is using. 
You can update the template by going to Settings>Digital Garden>Manage Site Template>Create PR.

**Comment by icytree** [comment]
I tested again today after updating the template and from what I could see, it seems to be working well with the light mode but not with the dark mode.
