### ISSUE TITLE
Unable to deploy to Vercel

### ISSUE THREAD

**Issue by octocatsup** [oleeskild/digitalgarden#180]
I am having issues when I click Deploy (to Vercel blue button). I receive this generic error in Vercel:

![image](https://github.com/oleeskild/obsidian-digital-garden/assets/75054337/dada8a44-ff11-4e9c-9c49-fd679fb838d6)

I have tried to deploy your template multiple times over the past few weeks and every instance ends the same way (the error shown).

I first used the granular access token, then tried the less restrictive access token, I created my repo first and then deployed it to Vercel. I tried a few other things. I am not unfamiliar with web development, but I am definitely not a pro. This has me baffled.

**Comment by oleeskild** [comment]
I've just tested using the Deploy button to Vercel, and it seems to be working now. It was probably just some temporary error with Vercel when you first tried. Try again now and see if it works as expected this time. I'm closing the issue, but let me know if it for some reason still doesn't work.
