### ISSUE TITLE
Links to headers are rendered as tags and are broken

### ISSUE THREAD

**Issue by bayang** [oleeskild/digitalgarden#185]
When I use a link that points to a header inside the same note, like this : 

```
Ce système motorise aussi le jeu [[#hostille]].
```

It is rendered as : 

```
<a class="tag" onclick="toggleTagSearch(this)" data-content="#hostile">#hostile</a>
```

Which means it is styled as a tag and when it is clicked it does not direct the user to the header but opens the search bar instead.

![Screenshot_20230626_175337](https://github.com/oleeskild/digitalgarden/assets/11558944/1d0e03e8-dc41-4426-9be1-3bd59cb9a960)

I think that the problem could be the "taggify" filter in the .eleventy.js file. : 

```
eleventyConfig.addFilter("taggify", function (str) {
    return (
      str &&
      str.replace(tagRegex, function (match, precede, tag) {
        return `${precede}<a class="tag" onclick="toggleTagSearch(this)" data-content="${tag}">${tag}</a>`;
      })
    );
  });
```

**Comment by F4bbi** [comment]
A simple workaround I use to avoid the problem is to use '|' to rename the link, in your case like [[#hostile|hostile]].

**Comment by bayang** [comment]
Hum weird, I tried this at first but when I went to check my deployed instance on vercel links were still broken.
But now that I check 2 hours later, links are fine...
I guess I have been bitten by a cache on vercel's side or in my browser.

We can close this, even if it's only a workaround.

Thanks for your help anyway @F4bbi .
