### ISSUE TITLE
Support for robots.txt

### ISSUE THREAD

**Issue by wheresalice** [oleeskild/digitalgarden#191]
It would be great if we could make it easy to manage a robots.txt file. Specifically, I want to be able to easily block the Googlebot.

As I understand it, this requires some configuration in .eleventy.js which would be overwritten by any PRs to update the template:

```js
eleventyConfig.addPassthroughCopy({ 'src/robots.txt': '/robots.txt' });
```

**Comment by oleeskild** [comment]
You should be able to achieve this by adding that line in the `src/helpers/userSetup.js` as described [here](https://dg-docs.ole.dev/advanced/configure-build-pipeline/)
