### ISSUE TITLE
[Add Feature] Add “dg-publish” properties to all/specific documents with one click.

### ISSUE THREAD

**Issue by JiaHuann** [oleeskild/digitalgarden#261]
Hi,there:
I have lots of md format docs, when i use this for obsidian,i have to add "dg-publish" manually.
Then, I write a shell script to add this tag to all docs.
I want to integrated this to this obsidian plug-in.
Want do you think?

**Comment by johndsmith2024** [comment]
Another option to consider: [GitHub - fez-github/obsidian-multi-properties: Plugin for Obsidian that allows user to add properties to multiple notes at once.](https://github.com/fez-github/obsidian-multi-properties)

**Comment by JiaHuann** [comment]
> Another option to consider: [GitHub - fez-github/obsidian-multi-properties: Plugin for Obsidian that allows user to add properties to multiple notes at once.](https://github.com/fez-github/obsidian-multi-properties)

Thanks.
