### ISSUE TITLE
link to other notes with display text seems to generate a wrong link

### ISSUE THREAD

**Issue by snnooze** [oleeskild/digitalgarden#27]
Hello,

I just start to use your digital garden on netlify and I have a little problem.
All works perfectly except the "link to other notes", maybe I don't use it correctly ?

If I use : 

`[[link to other note]]`

The generated url on my digital garden is ok but when I add a display text to my link : 

`[[link to other note | display text]]`

The generated link on the page lead to a 404 error.

It seems if I add a display text the url will always be 

"/notes/name-of-the-file" (Always starting with **notes** ans with the little **-** )

instead of 

"/subfolder name/other subfolders/name of the file" (without **notes** at the beginig and without the little **-**)

Thanks fo all the work you've done.
My english is not perfect but I hop I'll be understandable.

Have a nice day :)

**Comment by oleeskild** [comment]
I think its because you have a space after the filename. Try this and see if that works: 
[[link to other note|display text]]

**Comment by snnooze** [comment]
Yes, the space was the problem, sorry.

Thanks for your help.
