### ISSUE TITLE
Supporting for title from frontmatter

### ISSUE THREAD

**Issue by uroybd** [oleeskild/digitalgarden#30]
It is pretty normal to add a `title` to the frontmatter. Many static site generator uses this. A significant advantage of this over a filename is that some characters (e.g. `:`) are not allowed in the filename.

I propose to add support for `title` and falling back to `fileSlug` if unavailable throughout the site.

Since, I've already implemented it, I think I can organize the things and open a PR if you are fine with the idea.

**Comment by oleeskild** [comment]
I agree, a PR would be great.
By default, the title attribute isn't propagated to the template unless the "Let all frontmatter through"-setting is enabled. But I think it would make sense to let this propagate by default if this feature is implemented. Do you agree?

**Comment by uroybd** [comment]
> I agree, a PR would be great.
> By default, the title attribute isn't propagated to the template unless the "Let all frontmatter through"-setting is enabled. But I think it would make sense to let this propagate by default if this feature is implemented. Do you agree?

Of course it should by default, I open a PR.
