### ISSUE TITLE
Images and other media

### ISSUE THREAD

**Issue by dmje** [oleeskild/digitalgarden#37]
Is there a trick to publishing media / images / etc that are included in notes?

**Comment by oleeskild** [comment]
Just paste images like you normally would in Obsidian. It should be embedded in the page automatically. Is it not working?

**Comment by dmje** [comment]
Don't think so - the source is showing a reference but the image itself isn't there...

![Screenshot 2023-01-09 at 13 29 42](https://user-images.githubusercontent.com/64837/211319287-33563b72-ca16-481a-8309-991c4f6d1960.png)

**Comment by oleeskild** [comment]
Can you send an example of how the text looks in the original markdown file in obsidian?

**Comment by dmje** [comment]
Sure, here’s the sandbox file.

I noticed because I was trying to embed mp3’s which I guess aren’t working for the same reason…?



_____________

Mike Ellis / Director / Thirty8 Digital

***@***.***
Thirty8 Digital: a small but perfectly formed digital agency

An easy to use web publishing platform for museums: https://themuseumplatform.com

Tel: 0800 808 54 38
Mob: 07810 487 423
Telegram: https://t.me/thirty8digital
Web: thirty8.co.uk

Thirty8 Digital / Registered in England / Registered Company Number: 07646144

**Comment by dmje** [comment]
Looks like that file didn't arrive, here it is 

[Sandbox.md](https://github.com/oleeskild/digitalgarden/files/10373620/Sandbox.md)

**Comment by Tomaubier** [comment]
I'm also looking into ways to include `.mp4` videos and pdf documents. Is there any workaround for that?
Best

**Comment by oleeskild** [comment]
Only images are currently supported @Tomaubier . If you want to include PDFs or video files, there is a discussion about how to do it here: https://github.com/oleeskild/obsidian-digital-garden/discussions/117

**Comment by oleeskild** [comment]
@dmje I've found the bug. Embedded images on the form ![](image%20path.png) did not work when the image path is url encoded, which happens if for example the image path has a space in it. I've released version 2.35.1 of the plugin, which should fix the issue you're having with images. Let me know if that fixes it for you.

**Comment by dmje** [comment]
@oleeskild ace, thank you - this works! Now to wrangle some mp3s, which I understand have to be hosted separately...

Thanks for your work, great plugin!

**Comment by oleeskild** [comment]
Great! Yep, currently the need to be hosted separately. 

Thanks!

**Comment by jrtx0** [comment]
I use version:2.45.2 plugin. when image path has a space in it, embedded images didn't work.

**Comment by jrtx0** [comment]
> @dmje I've found the bug. Embedded images on the form ![](image%20path.png) did not work when the image path is url encoded, which happens if for example the image path has a space in it. I've released version 2.35.1 of the plugin, which should fix the issue you're having with images. Let me know if that fixes it for you.

I use version:2.45.2 plugin. when image path has a space in it, embedded images didn't work.
