### ISSUE TITLE
Links containing commas do not render

### ISSUE THREAD

**Issue by ThatOtherAndrew** [oleeskild/digitalgarden#4]
A couple of my links stopped working recently, and after some testing, it seems like all links containing commas render as plain text instead of as a link. I'm not sure as to the cause.

**Comment by oleeskild** [comment]
Right, I was too quick when adding this. I thought that filenames was not allowed to contain ",". But they are. I just released a quickfix, but I'll implement a more robust solution when I have the time. Thanks for letting me know!

No worries, it's not very important which repo you open issues in. 

Is it working for you again now?
