### ISSUE TITLE
Slash in tags in content

### ISSUE THREAD

**Issue by uroybd** [oleeskild/digitalgarden#48]
Obsidian supports slash in tags. I thought it didn't and modified the regex accordingly. Can you please update the regex in both taggify and search tag's regex (both in `.elventy.js`) to this?

```js
/(^|\s|\>)(#[^\s!@#$%^&*()=+\.,\[{\]};:'"?><]+)(?!([^<]*>))/g
```

**Comment by oleeskild** [comment]
Right. Thanks, I've updated the template!
