### ISSUE TITLE
Global Graph

### ISSUE THREAD

**Issue by uroybd** [oleeskild/digitalgarden#57]
I was toying with the Graph implementation and have implemented the Global Graph. It will also eliminate Backlink and OutboundLink search for every note and put them in a graph JSON file to be used by everyone.

Eventually, we'll be able to add a depth slider and other fancy things.

It will require some UI polishing though.

If you find it useful, I can prepare a PR.

You can check this out at https://hermitage.utsob.me

**Comment by uroybd** [comment]
Did some bug fixing, added the depth slider. It's pretty cool now.

**Comment by oleeskild** [comment]
This is great! It looks really good. The depth slider is a really nice touch. It would be really nice if you could create a PR for this!

**Comment by uroybd** [comment]
Great! I'm polishing it up and will send a PR once the current PR get merged.
