### ISSUE TITLE
MathJax and backslashes

### ISSUE THREAD

**Issue by yannick42** [oleeskild/digitalgarden#6]
Hello,

Before all, Thanks a lot for this plugin !

It seems there's an issue with MathJax, eg. with the two backslashes used to create a new line in a matrix, one of them is deleted so no rows are created :
![image](https://user-images.githubusercontent.com/7803246/159453105-98be83d8-218a-4d74-b87a-da374df49900.png)

(If I add four backslashes it works, but it adds unnecessary rows in Obsidian)

EDIT: But sometimes it render correctly :
```
$R(\theta)=\begin{bmatrix}\cos\theta&-\sin\theta\\\sin\theta&\cos\theta\end{bmatrix}$
```
![image](https://user-images.githubusercontent.com/7803246/159472107-0b751cf1-d3b7-406f-bddf-06967ac89b77.png)

It's when I add spaces around the `\\` that it fails and display the 4 elements on a line

**Comment by hxhc** [comment]
I think double backslashes could be replaced by `\newline`. Check out my [notes](https://hxhc-notes.netlify.app/3-web-clip/mathjax-test/), and I gave an example. You can also refer this [issue](https://github.com/mathjax/MathJax/issues/2312#issuecomment-1034001223) for more details.

**Comment by yannick42** [comment]
Oh ok, it works very well like that. Thanks.
