### ISSUE TITLE
Disable/Enable favicon in Filetree or Navbar with custom components

### ISSUE THREAD

**Issue by missymissprim** [oleeskild/digitalgarden#66]
I love the implementation of adding custom components to the site ♥️. It’s been a big help as I develop/customize my digital garden for D&D.

I was wondering if it would be possible to include custom components in the Filetree sidebar and/or Navbar, so that when I do a pull request via Obsidian to update my repository, I do not need to worry about losing custom code.

**Original Code**
<img width="1217" alt="Original" src="https://user-images.githubusercontent.com/107353366/217375021-8746e4fa-0baa-41fd-8218-82cf955d168a.png">

**My Code**
<img width="1217" alt="My Code" src="https://user-images.githubusercontent.com/107353366/217375018-a02989bc-ed6b-4ac0-aed0-05a161295eee.png">

**Comment by oleeskild** [comment]
Great to hear! 😄  We've just released a new version of the template, where @uroybd has added new slots for both the sidebar and the filetree. Details are available [in the documentation](https://dg-docs.ole.dev/advanced/adding-custom-components/). That should enable you to customize it how you want it. Let me know if it is sufficient or not

**Comment by missymissprim** [comment]
@oleeskild @uroybd Thank you so much!

I did try it and it doesn’t seem to be working. I created the files necessary following the documentation (src/site/_includes/components/user/filetree/beforeTitle/<filename>.njk), but it none of the elements have shown up.

**Comment by uroybd** [comment]
> @oleeskild @uroybd Thank you so much!
> 
> I noticed it only worked for the top navbar and not the filetree sidebar. Other than that it’s perfect. You guys are awesome!
> 

I'll investigate it.

**Comment by missymissprim** [comment]
@oleeskild @uroybd You guys are awesome!
