### ISSUE TITLE
Admonitions with empty title

### ISSUE THREAD

**Issue by yannick42** [oleeskild/digitalgarden#7]
Small issue : on Obsidian when the title property is set empty, the title disappear, but it's not the case on the generated pages.

**Comment by oleeskild** [comment]
Hi, thanks for showing an interest in the project!
I've just released a new version where this has been added. Let me know if it's solving your need or not. (Remember to also update the template by using the "Manage time template" button in the digital garden settings)

**Comment by yannick42** [comment]
Thanks, it works well
