### ISSUE TITLE
Graph only working for pages without spaces or other non-latin characters

### ISSUE THREAD

**Issue by stalegjelsten** [oleeskild/digitalgarden#75]
The graph view works for all my notes only containing latin characters like this one named "Radioaktivitet":
<img alt="screenshot showing a note with working graph" src="https://user-images.githubusercontent.com/5513050/219020980-4f4a100e-3b76-4109-8727-24736c109b27.png">

But, all my notes containing non-latin characters (like norwegian æ, ø or å) or spaces loads the graph view for the Home note (the home note is called "Ståles notater på nettet"). This is an example with a note called "Bakgrunnsstråling". As you can see, the graph view is centered on the home note.
<img alt="screenshot showing note with graph centered on home note" src="https://user-images.githubusercontent.com/5513050/219021345-a08d82a0-7800-433e-a742-664fc6589818.png">

I experience the same problem with notes with file names containing spaces.

I have the slugify note URL setting turned off as instructed because of the non-english characters.
<img alt="screenshot showing settings" src="https://user-images.githubusercontent.com/5513050/219021805-da8db6c7-1cfe-4f17-b035-2d2e75551f1a.png">

**Comment by oleeskild** [comment]
Thanks for letting me know! I've just released a new version of the template (1.42.0) which should fix this issue. If you update that, it should start working. Let me know how it works out! (See [updating the template](https://dg-docs.ole.dev/getting-started/06-updating-the-template/) in the docs for how to do that).

Also: For æøå you actually don't need to turn off the Slugify Note URL, as these are handled by converting them to "ae", "oe" and "a". I realize the description in the setting is a bit unprecise. It's mainly languages like Chinese and Russian that have issues.

**Comment by stalegjelsten** [comment]
Thank you! It works perfectly!
