### ISSUE TITLE
[Feature Request] Display of checkboxes

### ISSUE THREAD

**Issue by yannick42** [oleeskild/digitalgarden#8]
The checkboxes appear only as text `[x]`, is it possible to add them in HTML, with their saved state ?
Thanks

**Comment by oleeskild** [comment]
Hi, thanks for showing an interest in the project!
I've just released a new version where this has been added. Let me know if it's solving your need or not. (Remember to also update the template by using the "Manage time template" button in the digital garden settings)

**Comment by yannick42** [comment]
Perfect. Thanks for this plugin ! 😃
